language:
  - java
jdk:
  - openjdk8
script:
- ./gradlew test
- docker build -t applications .
- docker run -d -p 8080:8080 --name applications_container applications && sleep 10
- curl http://127.0.0.1:8080/v1/info
- docker stop applications_container
- docker rm applications_container
- docker rmi applications
